// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YandexMetrika;

#nullable disable

namespace YandexMetrika.Migrations.ByProductType
{
    [DbContext(typeof(ByProductTypeContext))]
    partial class ByProductTypeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("YandexMetrika.Entities.DomainTurnover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("Abs")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("abs");

                    b.Property<decimal?>("Cmc")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("cmc");

                    b.Property<decimal?>("Dkser")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("dkser");

                    b.Property<string>("DomainCorp")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("domain_corp");

                    b.Property<string>("DomainSecondCorp")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("domain_second_corp");

                    b.Property<decimal?>("Erlikid")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("erlikid");

                    b.Property<decimal?>("Fct")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("fct");

                    b.Property<decimal?>("Festo")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("festo");

                    b.Property<decimal?>("Fiztech")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("fiztech");

                    b.Property<decimal?>("Gazses")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("gazses");

                    b.Property<decimal?>("Gibriding")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("gibriding");

                    b.Property<decimal?>("Hamlet")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("hamlet");

                    b.Property<decimal?>("Hcme")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("hcme");

                    b.Property<decimal?>("Kamotsi")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("kamotsi");

                    b.Property<decimal?>("Krass")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("krass");

                    b.Property<decimal?>("Lindegaz")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("lindegaz");

                    b.Property<string>("ListInn")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("list_inn");

                    b.Property<decimal?>("Manometr")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("manometr");

                    b.Property<decimal?>("Manoterm")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("manoterm");

                    b.Property<decimal?>("Manotom")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("manotom");

                    b.Property<decimal?>("Metallrukav")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("metallrukav");

                    b.Property<decimal?>("Meter")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("meter");

                    b.Property<decimal?>("Metran")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("metran");

                    b.Property<decimal?>("Monnpo")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("monnpo");

                    b.Property<decimal?>("Monooo")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("monooo");

                    b.Property<decimal?>("Nps")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("nps");

                    b.Property<decimal?>("Nta")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("nta");

                    b.Property<decimal?>("Parker")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("parker");

                    b.Property<decimal?>("Rosma")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("rosma");

                    b.Property<decimal?>("Shtauf")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("shtauf");

                    b.Property<decimal?>("Shver")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("shver");

                    b.Property<decimal?>("Sigm")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("sigm");

                    b.Property<decimal?>("Spechcc")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("spechcc");

                    b.Property<decimal?>("Taikan")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("taikan");

                    b.Property<decimal?>("Tatkompl")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("tatkompl");

                    b.Property<decimal?>("Teplokont")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("teplokont");

                    b.Property<decimal?>("Turnover")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("turnover");

                    b.Property<decimal?>("Umas")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("umas");

                    b.Property<decimal?>("Ural")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("ural");

                    b.Property<decimal?>("Vsp")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("vsp");

                    b.Property<decimal?>("Wika")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("wika");

                    b.Property<decimal?>("Yok")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("yok");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DomainCorp" }, "domain_corp")
                        .IsUnique();

                    b.HasIndex(new[] { "DomainSecondCorp" }, "domain_sec");

                    b.ToTable("domain_turnover", (string)null);
                });

            modelBuilder.Entity("YandexMetrika.Entities.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DateCreate")
                        .HasColumnType("date")
                        .HasColumnName("date_create");

                    b.Property<string>("Email1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("SourceCreate")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("source_create");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email1" }, "email")
                        .IsUnique();

                    b.ToTable("emails", (string)null);
                });

            modelBuilder.Entity("YandexMetrika.Entities.InnDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DomainCorp")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("domain_corp");

                    b.Property<string>("DomainSecondCorp")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("domain_second_corp");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("inn");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DomainCorp", "DomainSecondCorp" }, "domains");

                    b.HasIndex(new[] { "Inn" }, "inn");

                    b.ToTable("inn_domain", (string)null);
                });

            modelBuilder.Entity("YandexMetrika.Entities.Main", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("Abs")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("abs");

                    b.Property<decimal?>("Cmc")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("cmc");

                    b.Property<DateOnly?>("DateCreate")
                        .HasColumnType("date")
                        .HasColumnName("date_create");

                    b.Property<decimal?>("Dkser")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("dkser");

                    b.Property<string>("DomainCorp")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("domain_corp");

                    b.Property<string>("DomainSecondCorp")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("domain_second_corp");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<decimal?>("Erlikid")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("erlikid");

                    b.Property<decimal?>("Fct")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("fct");

                    b.Property<decimal?>("Festo")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("festo");

                    b.Property<decimal?>("Fiztech")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("fiztech");

                    b.Property<decimal?>("Gazses")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("gazses");

                    b.Property<decimal?>("Gibriding")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("gibriding");

                    b.Property<decimal?>("Hamlet")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("hamlet");

                    b.Property<decimal?>("Hcme")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("hcme");

                    b.Property<decimal?>("Kamotsi")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("kamotsi");

                    b.Property<decimal?>("Krass")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("krass");

                    b.Property<decimal?>("Lindegaz")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("lindegaz");

                    b.Property<string>("ListInn")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("list_inn");

                    b.Property<decimal?>("Manometr")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("manometr");

                    b.Property<decimal?>("Manoterm")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("manoterm");

                    b.Property<decimal?>("Manotom")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("manotom");

                    b.Property<decimal?>("Metallrukav")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("metallrukav");

                    b.Property<decimal?>("Meter")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("meter");

                    b.Property<decimal?>("Metran")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("metran");

                    b.Property<decimal?>("Monnpo")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("monnpo");

                    b.Property<decimal?>("Monooo")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("monooo");

                    b.Property<decimal?>("Nps")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("nps");

                    b.Property<decimal?>("Nta")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("nta");

                    b.Property<decimal?>("Parker")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("parker");

                    b.Property<decimal?>("Rosma")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("rosma");

                    b.Property<decimal?>("Shtauf")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("shtauf");

                    b.Property<decimal?>("Shver")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("shver");

                    b.Property<decimal?>("Sigm")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("sigm");

                    b.Property<string>("SourceCreate")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("source_create");

                    b.Property<decimal?>("Spechcc")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("spechcc");

                    b.Property<decimal?>("Taikan")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("taikan");

                    b.Property<decimal?>("Tatkompl")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("tatkompl");

                    b.Property<decimal?>("Teplokont")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("teplokont");

                    b.Property<decimal?>("Turnover")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("turnover");

                    b.Property<decimal?>("Umas")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("umas");

                    b.Property<decimal?>("Ural")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("ural");

                    b.Property<decimal?>("Vsp")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("vsp");

                    b.Property<decimal?>("Wika")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("wika");

                    b.Property<decimal?>("Yok")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("yok");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DomainCorp" }, "domain");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique()
                        .HasDatabaseName("email1");

                    b.ToTable("main", (string)null);
                });

            modelBuilder.Entity("YandexMetrika.Entities.MainEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("Abs")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("abs");

                    b.Property<decimal?>("Cmc")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("cmc");

                    b.Property<DateOnly?>("DateCreate")
                        .HasColumnType("date")
                        .HasColumnName("date_create");

                    b.Property<decimal?>("Dkser")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("dkser");

                    b.Property<string>("DomainCorp")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("domain_corp");

                    b.Property<string>("DomainSecondCorp")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("domain_second_corp");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<decimal?>("Erlikid")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("erlikid");

                    b.Property<decimal?>("Fct")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("fct");

                    b.Property<decimal?>("Festo")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("festo");

                    b.Property<decimal?>("Fiztech")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("fiztech");

                    b.Property<decimal?>("Gazses")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("gazses");

                    b.Property<decimal?>("Gibriding")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("gibriding");

                    b.Property<decimal?>("Hamlet")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("hamlet");

                    b.Property<decimal?>("Hcme")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("hcme");

                    b.Property<decimal?>("Kamotsi")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("kamotsi");

                    b.Property<decimal?>("Krass")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("krass");

                    b.Property<decimal?>("Lindegaz")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("lindegaz");

                    b.Property<string>("ListInn")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("list_inn");

                    b.Property<decimal?>("Manometr")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("manometr");

                    b.Property<decimal?>("Manoterm")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("manoterm");

                    b.Property<decimal?>("Manotom")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("manotom");

                    b.Property<decimal?>("Metallrukav")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("metallrukav");

                    b.Property<decimal?>("Meter")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("meter");

                    b.Property<decimal?>("Metran")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("metran");

                    b.Property<decimal?>("Monnpo")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("monnpo");

                    b.Property<decimal?>("Monooo")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("monooo");

                    b.Property<decimal?>("Nps")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("nps");

                    b.Property<decimal?>("Nta")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("nta");

                    b.Property<decimal?>("Parker")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("parker");

                    b.Property<decimal?>("Rosma")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("rosma");

                    b.Property<decimal?>("Shtauf")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("shtauf");

                    b.Property<decimal?>("Shver")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("shver");

                    b.Property<decimal?>("Sigm")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("sigm");

                    b.Property<string>("SourceCreate")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("source_create");

                    b.Property<decimal?>("Spechcc")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("spechcc");

                    b.Property<decimal?>("Taikan")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("taikan");

                    b.Property<decimal?>("Tatkompl")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("tatkompl");

                    b.Property<decimal?>("Teplokont")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("teplokont");

                    b.Property<decimal?>("Turnover")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("turnover");

                    b.Property<decimal?>("Umas")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("umas");

                    b.Property<decimal?>("Ural")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("ural");

                    b.Property<decimal?>("Vsp")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("vsp");

                    b.Property<decimal?>("Wika")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("wika");

                    b.Property<decimal?>("Yok")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("yok");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique()
                        .HasDatabaseName("email2");

                    b.ToTable("main_emails", (string)null);
                });

            modelBuilder.Entity("YandexMetrika.Entities.MainPhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("Abs")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("abs");

                    b.Property<decimal?>("Cmc")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("cmc");

                    b.Property<DateOnly?>("DateCreate")
                        .HasColumnType("date")
                        .HasColumnName("date_create");

                    b.Property<decimal?>("Dkser")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("dkser");

                    b.Property<decimal?>("Erlikid")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("erlikid");

                    b.Property<decimal?>("Fct")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("fct");

                    b.Property<decimal?>("Festo")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("festo");

                    b.Property<decimal?>("Fiztech")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("fiztech");

                    b.Property<decimal?>("Gazses")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("gazses");

                    b.Property<decimal?>("Gibriding")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("gibriding");

                    b.Property<decimal?>("Hamlet")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("hamlet");

                    b.Property<decimal?>("Hcme")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("hcme");

                    b.Property<decimal?>("Kamotsi")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("kamotsi");

                    b.Property<decimal?>("Krass")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("krass");

                    b.Property<decimal?>("Lindegaz")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("lindegaz");

                    b.Property<string>("ListInn")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("list_inn");

                    b.Property<decimal?>("Manometr")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("manometr");

                    b.Property<decimal?>("Manoterm")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("manoterm");

                    b.Property<decimal?>("Manotom")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("manotom");

                    b.Property<decimal?>("Metallrukav")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("metallrukav");

                    b.Property<decimal?>("Meter")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("meter");

                    b.Property<decimal?>("Metran")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("metran");

                    b.Property<decimal?>("Monnpo")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("monnpo");

                    b.Property<decimal?>("Monooo")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("monooo");

                    b.Property<decimal?>("Nps")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("nps");

                    b.Property<decimal?>("Nta")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("nta");

                    b.Property<decimal?>("Parker")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("parker");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("phone");

                    b.Property<decimal?>("Rosma")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("rosma");

                    b.Property<decimal?>("Shtauf")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("shtauf");

                    b.Property<decimal?>("Shver")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("shver");

                    b.Property<decimal?>("Sigm")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("sigm");

                    b.Property<string>("SourceCreate")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("source_create");

                    b.Property<decimal?>("Spechcc")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("spechcc");

                    b.Property<decimal?>("Taikan")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("taikan");

                    b.Property<decimal?>("Tatkompl")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("tatkompl");

                    b.Property<decimal?>("Teplokont")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("teplokont");

                    b.Property<decimal?>("Turnover")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("turnover");

                    b.Property<decimal?>("Umas")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("umas");

                    b.Property<decimal?>("Ural")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("ural");

                    b.Property<decimal?>("Vsp")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("vsp");

                    b.Property<decimal?>("Wika")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("wika");

                    b.Property<decimal?>("Yok")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("yok");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("main_phones", (string)null);
                });

            modelBuilder.Entity("YandexMetrika.Entities.Minu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DomainMinus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("domain_minus");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DomainMinus" }, "minus");

                    b.ToTable("minus", (string)null);
                });

            modelBuilder.Entity("YandexMetrika.Entities.PhonesEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "emails");

                    b.ToTable("phones_email", (string)null);
                });

            modelBuilder.Entity("YandexMetrika.Entities.PhonesInn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DateCreate")
                        .HasColumnType("date")
                        .HasColumnName("date_create");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("inn");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("phone");

                    b.Property<string>("SourceCreate")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("source_create");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Inn" }, "inn")
                        .HasDatabaseName("inn1");

                    b.ToTable("phones_inn", (string)null);
                });

            modelBuilder.Entity("YandexMetrika.Entities.Turnover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("Abs")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("abs");

                    b.Property<decimal?>("Cmc")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("cmc");

                    b.Property<decimal?>("Dkser")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("dkser");

                    b.Property<decimal?>("Erlikid")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("erlikid");

                    b.Property<decimal?>("Fct")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("fct");

                    b.Property<decimal?>("Festo")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("festo");

                    b.Property<decimal?>("Fiztech")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("fiztech");

                    b.Property<decimal?>("Gazses")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("gazses");

                    b.Property<decimal?>("Gibriding")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("gibriding");

                    b.Property<decimal?>("Hamlet")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("hamlet");

                    b.Property<decimal?>("Hcme")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("hcme");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("inn");

                    b.Property<decimal?>("Kamotsi")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("kamotsi");

                    b.Property<decimal?>("Krass")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("krass");

                    b.Property<decimal?>("Lindegaz")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("lindegaz");

                    b.Property<decimal?>("Manometr")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("manometr");

                    b.Property<decimal?>("Manoterm")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("manoterm");

                    b.Property<decimal?>("Manotom")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("manotom");

                    b.Property<decimal?>("Metallrukav")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("metallrukav");

                    b.Property<decimal?>("Meter")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("meter");

                    b.Property<decimal?>("Metran")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("metran");

                    b.Property<decimal?>("Monnpo")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("monnpo");

                    b.Property<decimal?>("Monooo")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("monooo");

                    b.Property<decimal?>("Nps")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("nps");

                    b.Property<decimal?>("Nta")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("nta");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("organization_name");

                    b.Property<decimal?>("Parker")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("parker");

                    b.Property<decimal?>("Rosma")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("rosma");

                    b.Property<decimal?>("Shtauf")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("shtauf");

                    b.Property<decimal?>("Shver")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("shver");

                    b.Property<decimal?>("Sigm")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("sigm");

                    b.Property<decimal?>("Spechcc")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("spechcc");

                    b.Property<decimal?>("SumTurnover")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("sum_turnover");

                    b.Property<decimal?>("Taikan")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("taikan");

                    b.Property<decimal?>("Tatkompl")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("tatkompl");

                    b.Property<decimal?>("Teplokont")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("teplokont");

                    b.Property<decimal?>("Umas")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("umas");

                    b.Property<decimal?>("Ural")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("ural");

                    b.Property<decimal?>("Vsp")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("vsp");

                    b.Property<decimal?>("Wika")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("wika");

                    b.Property<decimal?>("Yok")
                        .HasPrecision(20, 3)
                        .HasColumnType("decimal(20,3)")
                        .HasColumnName("yok");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Inn" }, "inn")
                        .HasDatabaseName("inn2");

                    b.ToTable("turnovers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
