// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YandexMetrika.Migrations
{
    [DbContext(typeof(YandexMetrikaContext))]
    [Migration("20230825065915_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            #pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("YandexMetrika.EntitiesYandexMetrika.AddLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime")
                        .HasColumnName("date_created");

                    b.Property<string>("Log")
                        .HasColumnType("text")
                        .HasColumnName("log");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("add_logs", (string)null);
                });

            modelBuilder.Entity("YandexMetrika.EntitiesYandexMetrika.InProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date_time");

                    b.Property<string>("EmailsMd5")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("emails_md5");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("order_status");

                    b.Property<string>("PhonesMd5")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Phones_md5");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("in_progress", (string)null);
                });
                #pragma warning restore 612, 618
        }
    }
}
